In [13]:
import numpy as np
import itertools
from pprint import pprint


n, k = 6, 3
G = np.array([
    [1, 0, 1, 1, 0, 1],
    [1, 0, 1, 0, 1, 0],
    [1, 1, 0, 1, 0, 0],
])
H = np.array([
    [1, 1, 0, 0, 1, 1],
    [0, 0, 1, 0, 1, 1],
    [0, 1, 0, 1, 0, 1],
])
msgs = np.array(list(itertools.product([0, 1], repeat=k)))
print(msgs.shape)
codewords = (msgs @ G) % 2
print(codewords)

for i in range(1, 6):
    print(f'len = {i}')
    syndromes = {}
    for word in codewords:
        # print(word[:i], (word[:i] @ H[:, :i].T) % 2)
        syndromes[tuple(word[:i])] = (word[:i] @ H[:, :i].T) % 2
    pprint(syndromes)

(8, 3)
[[0 0 0 0 0 0]
 [1 1 0 1 0 0]
 [1 0 1 0 1 0]
 [0 1 1 1 1 0]
 [1 0 1 1 0 1]
 [0 1 1 0 0 1]
 [0 0 0 1 1 1]
 [1 1 0 0 1 1]]
len = 1
{(0,): array([0, 0, 0], dtype=int32), (1,): array([1, 0, 0], dtype=int32)}
len = 2
{(0, 0): array([0, 0, 0], dtype=int32),
 (0, 1): array([1, 0, 1], dtype=int32),
 (1, 0): array([1, 0, 0], dtype=int32),
 (1, 1): array([0, 0, 1], dtype=int32)}
len = 3
{(0, 0, 0): array([0, 0, 0], dtype=int32),
 (0, 1, 1): array([1, 1, 1], dtype=int32),
 (1, 0, 1): array([1, 1, 0], dtype=int32),
 (1, 1, 0): array([0, 0, 1], dtype=int32)}
len = 4
{(0, 0, 0, 0): array([0, 0, 0], dtype=int32),
 (0, 0, 0, 1): array([0, 0, 1], dtype=int32),
 (0, 1, 1, 0): array([1, 1, 1], dtype=int32),
 (0, 1, 1, 1): array([1, 1, 0], dtype=int32),
 (1, 0, 1, 0): array([1, 1, 0], dtype=int32),
 (1, 0, 1, 1): array([1, 1, 1], dtype=int32),
 (1, 1, 0, 0): array([0, 0, 1], dtype=int32),
 (1, 1, 0, 1): array([0, 0, 0], dtype=int32)}
len = 5
{(0, 0, 0, 0, 0): array([0, 0, 0], dtype=int32),
 (0, 0, 